version: "3"

services:
  backend:
    container_name: power_trade_backend
    tty: true
    stdin_open: true
    restart: always
    build:
      context: .
    volumes:
      - ./:/app/
    ports:
      - "8000:8000"
    environment:
      - SENTRY_DSN=${SENTRY_DSN}
      - SECRET_KEY=${SECRET_KEY}
      - ENVIRONMENT=${ENVIRONMENT}
      - DB_URL=${DB_URL}

  frontend:
    container_name: power_trade_frontend
    image: nginx:alpine
    volumes:
      - ./dashboard:/usr/share/nginx/html
    ports:
      - "3000:80"
    depends_on:
      - backend
